### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by daltones** [Kuniwak/gulp-less-reporter#4]
I think dependencies in package.json are messed up.
1. The most important: "gulp-util" is **not** a devDependency, it's a **functional** dependency. This actually broke the plugin.
2. "gulp-less" is **not** a dependency. Of course it seems like there's no point using gulp-less-reporter without gulp-less, but it is possible.

**Comment by Kuniwak** [comment]
Thanks reporting.
Now, gulp-util is in dependency and gulp-less is in devDependency.
