### ISSUE TITLE
when is the next release that supports updated package.json organization?

### ISSUE THREAD

**Issue by ghost** [Kuniwak/gulp-less-reporter#6]
Since the latest tag in NPM doesn't have `gulp-util` as a dependency, running `npm instal gulp-less-reporter` will not install `gulp-util` as a node module and thus will cause errors in downstream projects.  

I see that this change is in master per the fix here
https://github.com/Kuniwak/gulp-less-reporter/commit/9198a3a49f77c7f909249190bab1da40bfe76f0d

Just wondering when a tagged release could be made.

Thanks!

**Comment by ghost** [comment]
hello @Kuniwak , just bumping for visibility.  Any thoughts on this?  Anything i can do to help?

**Comment by Kuniwak** [comment]
Sorry for late reply.

OK, I'm gonna fix it.

**Comment by ghost** [comment]
thanks @Kuniwak !

**Comment by Kuniwak** [comment]
Done: https://www.npmjs.com/package/gulp-less-reporter

**Comment by ghost** [comment]
great!  thanks for the quick turnaround @Kuniwak
